stop-words = "./slackwire/datasets/stopwords.txt"
prefix = "./slackwire/datasets"
dataset = "combined"
corpus = "line.toml"
query-judgements = "qrels.txt"
index = "idx"
[query-runner]
	query-id-start = 1
	query-path = "queries.txt"
[[analyzers]]
	filter = "default-unigram-chain"
	method = "ngram-word"
	ngram = 1
