index = "idx"
corpus = "line.toml"
stop-words = "/Users/bjones325/Documents/MS work/CS410/CourseProject/slackwire/datasets/stopwords.txt"
dataset = "slack"
query-judgements = "qrels.txt"
prefix = "./slackwire/datasets"
[query-runner]
	query-id-start = 1
	query-path = "queries.txt"
[[analyzers]]
	filter = "default-unigram-chain"
	ngram = 1
	method = "ngram-word"
