prefix = "."
stop-words = "stopwords.txt"

dataset = "slack_dataset"
corpus = "line.toml"
index = "slack_idx"

query-judgements = "slack-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "slack-queries.txt"
query-id-start = 1