prefix = "./slackwire/datasets"
stop-words = "./slackwire/datasets/stopwords.txt"

dataset = "slack"
corpus = "line.toml"
index = "idx"

query-judgements = "./slackwire/datasets/slack/qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "./slackwire/datasets/slack/queries.txt"
query-id-start = 1