prefix = "."
stop-words = "stopwords.txt"

dataset = "campuswire_dataset"
corpus = "line.toml"
index = "campuswire_idx"

query-judgements = "campuswire-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "campuswire-queries.txt"
query-id-start = 1