prefix = "."
stop-words = "stopwords.txt"

dataset = "combined_dataset"
corpus = "line.toml"
index = "combined_idx"

query-judgements = "combined-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "combined-queries.txt"
query-id-start = 1